### ISSUE TITLE
Tooltip comparison

### ISSUE THREAD

**Issue by CyberMew** [iCrawlerRPG/iCrawlerRPG.github.io#12]
It would be great to be able to compare an item in our inventory against the currently equipped stats. Simply showing it in brackets would be great enough, color coded would be even better.

When entering sell mode too, the tooltip should list if it's a weapon/armor for easier comparison and deciding which to keep, since it changes to just price.

Come to think of it, it would be great to be able to sort/separate the type with tabs.

**Comment by peterbrinck** [comment]
Thanks for your suggestions!
They've been added to our to-do
